"""inicando criacao

Revision ID: a3228a98940c
Revises: 
Create Date: 2023-03-17 19:16:42.231893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3228a98940c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=100), nullable=True),
    sa.Column('dt_nasc', sa.String(length=100), nullable=True),
    sa.Column('dt_ini', sa.String(length=100), nullable=True),
    sa.Column('duracao', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('csenha', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usu', sa.Integer(), nullable=True),
    sa.Column('id_foll', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_foll'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_usu'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usu', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usu'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
